### ISSUE TITLE
it doesn't work for html strings in IE

### ISSUE THREAD

**Issue by inspiraller** [ericelliott/jQuery.outerHTML#3]
If you wanted to get the outer html of say id="blog" in the following example:
$('<div><div id="blog">Some Content</div></div>').find('#blog').outerHTML();

After much messing around to get it working in ie, I created the following example:

$.fn.htmlStringOuterHTML = function() {  
        this.parent().find(this).wrap('<div/>');  
        return this.parent().html();
    };

I hope it helps.

**Comment by ericelliott** [comment]
Your solution will have performance implications because it doesn't fall back on native support, and it always manipulates the DOM, even if that isn't required. Also, doing the wrap will cause a remove and add of the code, meaning that any scripts contained in the DIV will be executed again -- and yours leaves a modified DOM because you don't subsequently .unwrap().

My plugin uses .wrap() only as a last resort, and it does do the .unwrap(), as well.

You should replace your solution with this fixed version, tested in IE6 - IE9, Firefox, Chrome, Safari. There's a working test case here: http://jsfiddle.net/dilvie/wdpBr/

**Comment by inspiraller** [comment]
Excellent. Yes, I realised this after I had posted it, and wish I
hadn't been so hasty. Thankyou for replying especially with a much
needed fix for another one of IEs failings.

On 6/22/12, Eric Hamilton
reply@reply.github.com
wrote:
